/*

CREATE USER BLOG 
IDENTIFIED BY abc123#;

GRANT ADM_PARALLEL_EXECUTE_TASK FROM BLOG;
GRANT APEX_ADMINISTRATOR_ROLE FROM BLOG;
GRANT AQ_ADMINISTRATOR_ROLE FROM BLOG;
GRANT AQ_USER_ROLE FROM BLOG;
GRANT AUTHENTICATEDUSER FROM BLOG;
GRANT CONNECT FROM BLOG;
GRANT CSW_USR_ROLE FROM BLOG;
GRANT CTXAPP FROM BLOG;
GRANT CWM_USER FROM BLOG;
GRANT DATAPUMP_EXP_FULL_DATABASE FROM BLOG;
GRANT DATAPUMP_IMP_FULL_DATABASE FROM BLOG;
GRANT DBA FROM BLOG;
GRANT DBFS_ROLE FROM BLOG;
GRANT DELETE_CATALOG_ROLE FROM BLOG;
GRANT EJBCLIENT FROM BLOG;
GRANT EXECUTE_CATALOG_ROLE FROM BLOG;
GRANT EXP_FULL_DATABASE FROM BLOG;
GRANT GATHER_SYSTEM_STATISTICS FROM BLOG;
GRANT HS_ADMIN_EXECUTE_ROLE FROM BLOG;
GRANT HS_ADMIN_ROLE FROM BLOG;
GRANT HS_ADMIN_SELECT_ROLE FROM BLOG;
GRANT IMP_FULL_DATABASE FROM BLOG;
GRANT JAVADEBUGPRIV FROM BLOG;
GRANT JAVAIDPRIV FROM BLOG;
GRANT JAVASYSPRIV FROM BLOG;
GRANT JAVAUSERPRIV FROM BLOG;
GRANT JAVA_ADMIN FROM BLOG;
GRANT JAVA_DEPLOY FROM BLOG;
GRANT JMXSERVER FROM BLOG;
GRANT LOGSTDBY_ADMINISTRATOR FROM BLOG;
GRANT MGMT_USER FROM BLOG;
GRANT OEM_ADVISOR FROM BLOG;
GRANT OEM_MONITOR FROM BLOG;
GRANT OLAPI_TRACE_USER FROM BLOG;
GRANT OLAP_DBA FROM BLOG;
GRANT OLAP_USER FROM BLOG;
GRANT OLAP_XS_ADMIN FROM BLOG;
GRANT ORDADMIN FROM BLOG;
GRANT OWB$CLIENT FROM BLOG;
GRANT OWB_DESIGNCENTER_VIEW FROM BLOG;
GRANT OWB_USER FROM BLOG;
GRANT RECOVERY_CATALOG_OWNER FROM BLOG;
GRANT RESOURCE FROM BLOG;
GRANT SCHEDULER_ADMIN FROM BLOG;
GRANT SELECT_CATALOG_ROLE FROM BLOG;
GRANT SPATIAL_CSW_ADMIN FROM BLOG;
GRANT SPATIAL_WFS_ADMIN FROM BLOG;
GRANT WFS_USR_ROLE FROM BLOG;
GRANT WM_ADMIN_ROLE FROM BLOG;
GRANT XDBADMIN FROM BLOG;
GRANT XDB_SET_INVOKER FROM BLOG;
GRANT XDB_WEBSERVICES FROM BLOG;
GRANT XDB_WEBSERVICES_OVER_HTTP FROM BLOG;
GRANT XDB_WEBSERVICES_WITH_PUBLIC FROM BLOG;
GRANT SYSDBA TO BLOG;

ALTER USER BLOG DEFAULT ROLE SYSDBA;

*/

CREATE TABLE BLOG.USUARIO
(
    CODIGO_USUARIO INT PRIMARY KEY, 
    NOME_USUARIO VARCHAR2(20) NOT NULL,
    SENHA_USUARIO VARCHAR2(20) NOT NULL, 
    ATIVO_USUARIO CHAR(1) NOT NULL
);

CREATE TABLE BLOG.CATEGORIA
(
    CODIGO_CATEGORIA INT PRIMARY KEY, 
    DESCRICAO_CATEGORIA VARCHAR2(30) NOT NULL,
    DATA_EXCLUSAO_CATEGORIA DATE
);

CREATE TABLE BLOG.POST
(
  CODIGO_POST INT PRIMARY KEY,
  TITULO_POST VARCHAR2(100)NOT NULL,
  CONTEUDO_POST CLOB NOT NULL,
  DATA_INCLUSAO_POST DATE DEFAULT SYSDATE NOT NULL,
  DATA_LIBERACAO_POST DATE DEFAULT SYSDATE NOT NULL,
  CODIGO_USUARIO INT NOT NULL REFERENCES BLOG.USUARIO(CODIGO_USUARIO),
  PRIVADO_POST CHAR(1) NOT NULL
);

CREATE TABLE BLOG.POST_CATEGORIA
(
    CODIGO_POST INT REFERENCES BLOG.POST(CODIGO_POST) NOT NULL, 
    CODIGO_CATEGORIA INT REFERENCES BLOG.CATEGORIA(CODIGO_CATEGORIA) NOT NULL,
    PRIMARY KEY (CODIGO_POST, CODIGO_CATEGORIA)
);

CREATE SEQUENCE BLOG.SEQ_USUARIO;

CREATE SEQUENCE BLOG.SEQ_CATEGORIA;

CREATE SEQUENCE BLOG.SEQ_POST;

CREATE TRIGGER BLOG.TRG_SEQ_USUARIO 
    BEFORE INSERT ON BLOG.USUARIO 
    FOR EACH ROW
DECLARE RECNUM INT; 
 BEGIN 
      SELECT BLOG.SEQ_USUARIO.NEXTVAL 
      INTO RECNUM 
      FROM DUAL 
      WHERE ROWNUM = 1; 
      
      :new.CODIGO_USUARIO := RECNUM; 
 END;
/

CREATE TRIGGER BLOG.TRG_SEQ_CATEGORIA 
    BEFORE INSERT ON BLOG.CATEGORIA
    FOR EACH ROW
DECLARE RECNUM INT; 
 BEGIN 
      SELECT BLOG.SEQ_CATEGORIA.NEXTVAL 
      INTO RECNUM 
      FROM DUAL 
      WHERE ROWNUM = 1; 
      
      :new.CODIGO_CATEGORIA := RECNUM; 
 END;
/

CREATE TRIGGER BLOG.TRG_SEQ_POST 
    BEFORE INSERT ON BLOG.POST
    FOR EACH ROW
DECLARE RECNUM INT; 
 BEGIN 
      SELECT BLOG.SEQ_POST.NEXTVAL 
      INTO RECNUM 
      FROM DUAL 
      WHERE ROWNUM = 1; 
      
      :new.CODIGO_POST := RECNUM; 
 END;
/

