//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.ProxyCategoria {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/WS.Model")]
    [System.SerializableAttribute()]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataExclusaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataExclusao {
            get {
                return this.DataExclusaoField;
            }
            set {
                if ((this.DataExclusaoField.Equals(value) != true)) {
                    this.DataExclusaoField = value;
                    this.RaisePropertyChanged("DataExclusao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCategoria.ICategoria")]
    public interface ICategoria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoria/Inserir", ReplyAction="http://tempuri.org/ICategoria/InserirResponse")]
        void Inserir(Site.ProxyCategoria.Categoria obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoria/Alterar", ReplyAction="http://tempuri.org/ICategoria/AlterarResponse")]
        void Alterar(Site.ProxyCategoria.Categoria obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoria/Excluir", ReplyAction="http://tempuri.org/ICategoria/ExcluirResponse")]
        void Excluir(Site.ProxyCategoria.Categoria obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoria/Selecionar", ReplyAction="http://tempuri.org/ICategoria/SelecionarResponse")]
        Site.ProxyCategoria.Categoria[] Selecionar();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriaChannel : Site.ProxyCategoria.ICategoria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaClient : System.ServiceModel.ClientBase<Site.ProxyCategoria.ICategoria>, Site.ProxyCategoria.ICategoria {
        
        public CategoriaClient() {
        }
        
        public CategoriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Inserir(Site.ProxyCategoria.Categoria obj) {
            base.Channel.Inserir(obj);
        }
        
        public void Alterar(Site.ProxyCategoria.Categoria obj) {
            base.Channel.Alterar(obj);
        }
        
        public void Excluir(Site.ProxyCategoria.Categoria obj) {
            base.Channel.Excluir(obj);
        }
        
        public Site.ProxyCategoria.Categoria[] Selecionar() {
            return base.Channel.Selecionar();
        }
    }
}
